[package]
name = "psychologist-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eliza = "2.0.0"
mysql = "23.0.1"
openai-api = "0.1.4"
teloxide = "0.12.0"
tokio = { version = "1.24.2", features = ["rt-multi-thread", "macros"] }